# Generated by Django 3.0.6 on 2020-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20200604_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
