# Generated by Django 3.0.6 on 2020-06-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0022_auto_20200626_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_brand', to='ad.Brand'),
        ),
    ]
