# Generated by Django 3.0.6 on 2020-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0028_auto_20200629_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Like New', 'Like New'), ('Good Condition', 'Good Condition'), ('Bad Condition', 'Bad Condition')], max_length=15, null=True),
        ),
    ]
